### ISSUE TITLE
compiler 相关的问题请教

### ISSUE THREAD

**Issue by LeiYao123** [yijinc/icon-garden#2]
首先非常感谢大佬，解决了我的大问题

我用你这个仓库代码运行 compiler 没问题可以正常把 svg 变成 react tsx 组件

但是有一个小问题就是 svg 有一些短横线连接的属性比如 `clip-path`, `fill-rule` 这样的在生成 react 组件时不会变成 驼峰写法，导致开发环境会有红色的warning，如下图所示，

另外我看 svgr 这样的工具在把 svg 转成react组件时也会把短横线连接的属性转为驼峰写法

![image](https://github.com/yijinc/icon-garden/assets/99799032/2295cbea-4b13-4799-b6cb-20f27aeb6038)

**Comment by yijinc** [comment]
这个确实这边没有处理，只做了颜色/尺寸的替代

**Comment by LeiYao123** [comment]
我发现用 eslint 的 --fix 可以帮我将 短横线连接的属性改为 驼峰
